5 new actions
StackStorm-Exchange/github pull request #46
Opened 2022-05-23 13:27 UTC by MarlonHeiber

* Add new ``github.add_repository_collaborator`` action which allows user to add a collaborator to repository.
* Add new ``github.check_user_repository_collaborator`` action which allows user to check if an user is a collaborator's repository.
* Add new ``github.get_repository_collaborators`` action which allows user to list the collaborators of repository.
* Add new ``github.add_update_repository_team`` action which allows user to add a team to repository.
* Add new ``github.check_team_permissions_for_repository`` action which allows user to check if a team has access to repositor

2022-05-23 15:22 UTC, armab requested changes
Thanks for the contribution!
Looks good.

Outside of semver, we'll also need to update the `pack.yaml` with the updated version.

2022-05-23 15:22 UTC, armab commented on CHANGES.md
> +## 2.1.2
Let's follow the https://semver.org/ and bump the minor version for the new features like this.
```suggestion
## 2.2.0
```

2022-07-08 18:34 UTC, MarlonHeiber commented
Hello @armab 
All suggestions for changes have already been made
Is something missing to approve/merge this PR?

2022-07-12 18:31 UTC, MarlonHeiber commented
> Thanks for the contribution! Looks good.
> 
> Outside of semver, we'll also need to update the `pack.yaml` with the new version.

path.yaml updated

2022-07-19 20:09 UTC, closed without merging